# -*- coding: utf-8 -*-
"""Spotify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPx1xA5cPBeN2j4KbT63fqzPhIqX0R2C
"""

!pip install spotipy

import pandas as pd
import argparse
import sys
import os
import subprocess
import json
import spotipy 
import spotipy.util as util
from spotipy.oauth2 import SpotifyClientCredentials

client_id = '00b16f9b852b406bb3a82d5d60475d61'
client_secret = 'cfcae9a1a9ce42e3a1f97d3d96d44bc8'

client_credentials_manager = SpotifyClientCredentials(client_id=client_id,
                                                      client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

username = 'spotifycharts'
playlist_id = '18P7DfWvx1bqeppz8UN8JZ'

#https://github.com/juandes/spotify-audio-features-data-experiment

def get_playlist_audio_features(username, playlist_id, sp):
    offset = 0
    songs = []
    items = []
    ids = []
    trname = []
    artname = []
    while True:
        content = sp.user_playlist_tracks(username, playlist_id, fields=None, limit=100, offset=offset)
        songs += content['items']
        if content['next'] is not None:
            offset += 100
        else:
            break
    for i in songs:
        ids.append(i['track']['id'])
        trname.append(i['track']['name']) 
        artname.append(i['track']['artists'][0]['name'])

    index = 0
    audio_features = []
    while index < len(ids):
        audio_features += sp.audio_features(ids[index:index + 50])
        index += 50

    features_list = []
    for features in audio_features:
        features_list.append([features['energy'], features['liveness'],
                              features['tempo'], features['speechiness'],
                              features['acousticness'], features['instrumentalness'],
                              features['time_signature'], features['danceability'],
                              features['key'], features['duration_ms'],
                              features['loudness'], features['valence'],
                              features['mode'], features['type'],
                              features['uri']])

    df = pd.DataFrame(features_list, columns=['energy', 'liveness',
                                              'tempo', 'speechiness',
                                              'acousticness', 'instrumentalness',
                                              'time_signature', 'danceability',
                                              'key', 'duration_ms', 'loudness',
                                              'valence', 'mode', 'type', 'uri'])
    df['name_artist'] = artname
    df['name_track'] = trname
    df.to_csv('{}-{}.csv'.format(username, playlist_id), index=False)

get_playlist_audio_features(username, playlist_id, sp)